services:
  bubbaflix:
    image: ghcr.io/jsanderstechnologies/bubbaflix-media-center:latest
    container_name: bubbaflix
    restart: unless-stopped
    ports:
      - "5150:5150"
    volumes:
      - ./data:/app/data
      - /etc/resolv.conf:/etc/resolv.conf:ro
    environment:

      - NODE_ENV=production
      - PORT=5150
      - TMDB_KEY=
      - TORBOX_API_KEY=
      - AIOSTREAMS_URL=
    networks:
      - bubbaflix-net

  aiostreams:
    image: viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./aiostreams-data:/app/data
    networks:
      - bubbaflix-net

networks:
  bubbaflix-net:
    driver: bridge


